apiVersion: apps/v1
kind: Deployment
metadata:
  name: windows-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: windows-app
  template:
    metadata:
      labels:
        app: windows-app
    spec:
      containers:
      - name: windows-container
        image: kiranacrdevops.azurecr.io/winapp/caliiis
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: windows-service
spec:
  selector:
    app: windows-app
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
